/**
 * Created by zhangzhonghua on 2016/9/12.
 */
public enum DataColumnType {
    CHAR,VARCHAR,VARCHAR2,TEXT,CLOB,STRING,
    TINYINT, SMALLINT,SHORT,INT,INTEGER,BIGINT,LONG,FLOAT,DOUBLE,NUMERIC,DECIMAL,
    DATE,TIME,DATETIME,TIMESTAMP,
    BLOB,BINARY,BYTE,
    ARRAY,
    BOOLEAN,
    NULL,
    UNKNOWN
}
